"""
CPU smoke tests for AF-FCL.

Verifies that each dataset configuration starts and completes without errors
on CPU.  Minimum iterations are used so that at least one full training round
is exercised per task without being slow:

    num_glob_iters = N_TASKS   (1 global round per task)
    local_epochs   = 1         (one pass over local data per round)

Dataset / split-file availability
----------------------------------
EMNIST-Letters-shuffle
    Dataset downloaded automatically by torchvision.
    Split file auto-generated on first run by dataset.py → always runs.

EMNIST-Letters  /  EMNIST-Letters-malicious
    Dataset downloaded automatically.
    Split file must exist at:
      datasets/PreciseFCL/data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl
    No generator script is bundled; supply the .pkl manually.
    → Test is skipped if the file is missing.

CIFAR100
    Dataset downloaded automatically.
    Split file generated by:  python generate_cifar100_split.py
    → Test is skipped if the file is missing.

MNIST-SVHN-FASHION
    Datasets must be pre-downloaded into datasets/PreciseFCL/ (download=False).
    Split file must exist at:
      datasets/PreciseFCL/data_split/MNISTSVHNFASHION_split_cn10_tn6_cet3_s2571.pkl
    → Test is skipped if the file is missing.

Usage
-----
With pytest (recommended):
    pip install pytest
    pytest test_cpu.py -v

Without pytest:
    python test_cpu.py
"""

import os
import sys
import subprocess

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
WORKSPACE = os.path.dirname(os.path.abspath(__file__))
PYTHON = sys.executable
SPLIT_DIR = os.path.join(WORKSPACE, "datasets", "PreciseFCL", "data_split")

_EMNIST_SPLIT   = os.path.join(SPLIT_DIR, "EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl")
_CIFAR_SPLIT    = os.path.join(SPLIT_DIR, "CIFAR100_split_cn10_tn4_cet20_s2571.pkl")
_MSF_SPLIT      = os.path.join(SPLIT_DIR, "MNISTSVHNFASHION_split_cn10_tn6_cet3_s2571.pkl")

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def _run(dataset, data_split_file, n_tasks, extra_args=None):
    """
    Invoke main.py on CPU with minimal settings.

    num_glob_iters is set to n_tasks so that epoch_per_task = int(n_tasks/n_tasks) = 1,
    ensuring the inner training loop runs at least once per task.
    Asserts the process exits with code 0.
    """
    cmd = [
        PYTHON,
        os.path.join(WORKSPACE, "main.py"),
        "--device",           "cpu",
        "--dataset",          dataset,
        "--datadir",          "datasets/PreciseFCL/",
        "--data_split_file",  data_split_file,
        "--num_glob_iters",   str(n_tasks),
        "--local_epochs",     "1",
        "--debug",
        "--target_dir_name",  os.path.join(WORKSPACE, "test_output"),
    ]
    if extra_args:
        cmd += extra_args

    result = subprocess.run(cmd, capture_output=True, text=True, cwd=WORKSPACE)

    if result.returncode != 0:
        # Print last 4000 chars to stay readable
        print("=== STDOUT (tail) ===\n" + result.stdout[-4000:])
        print("=== STDERR (tail) ===\n" + result.stderr[-4000:])

    assert result.returncode == 0, (
        f"[{dataset}] main.py exited with code {result.returncode}"
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_emnist_letters_shuffle():
    """
    EMNIST-Letters-shuffle
    ----------------------
    * Dataset:    downloaded automatically by torchvision.
    * Split file: auto-generated inside dataset.py if missing.

    This test always runs; it only needs an internet connection on first use.
    """
    _run(
        dataset="EMNIST-Letters-shuffle",
        data_split_file="data_split/EMNIST_letters_shuffle_split_cn8_tn6_cet2_cs2_s2571.pkl",
        n_tasks=6,
        extra_args=[
            "--flow_lr",           "1e-3",
            "--k_loss_flow",       "0.05",
            "--k_flow_lastflow",   "0.02",
            "--flow_explore_theta","0.5",
        ],
    )


@pytest.mark.skipif(
    not os.path.exists(_EMNIST_SPLIT),
    reason=(
        "EMNIST-Letters split file not found at "
        "datasets/PreciseFCL/data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl  "
        "– supply the .pkl file manually."
    ),
)
def test_emnist_letters():
    """
    EMNIST-Letters
    --------------
    Requires the pre-generated split file at the path above.
    """
    _run(
        dataset="EMNIST-Letters",
        data_split_file="data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl",
        n_tasks=6,
        extra_args=[
            "--flow_lr",           "1e-4",
            "--k_loss_flow",       "0.5",
            "--k_flow_lastflow",   "0.4",
            "--flow_explore_theta","0",
        ],
    )


@pytest.mark.skipif(
    not os.path.exists(_EMNIST_SPLIT),
    reason=(
        "EMNIST-Letters split file not found "
        "(shared with EMNIST-Letters-malicious) – supply the .pkl file manually."
    ),
)
def test_emnist_letters_malicious():
    """
    EMNIST-Letters-malicious
    ------------------------
    Uses the same split file as EMNIST-Letters.
    Runs with 1 malicious client to exercise the noisy-label code path.
    """
    _run(
        dataset="EMNIST-Letters-malicious",
        data_split_file="data_split/EMNIST_letters_split_cn8_tn6_cet2_cs2_s2571.pkl",
        n_tasks=6,
        extra_args=[
            "--malicious_client_num", "1",
            "--flow_lr",              "1e-3",
            "--k_loss_flow",          "0.5",
            "--k_flow_lastflow",      "0.1",
            "--flow_explore_theta",   "0.5",
        ],
    )


@pytest.mark.skipif(
    not os.path.exists(_CIFAR_SPLIT),
    reason=(
        "CIFAR100 split file not found – run:  python generate_cifar100_split.py"
    ),
)
def test_cifar100():
    """
    CIFAR100
    --------
    * Dataset:    downloaded automatically by torchvision.
    * Split file: generated by running  python generate_cifar100_split.py
    """
    _run(
        dataset="CIFAR100",
        data_split_file="data_split/CIFAR100_split_cn10_tn4_cet20_s2571.pkl",
        n_tasks=4,
        extra_args=[
            "--flow_lr",           "5e-3",
            "--k_loss_flow",       "0.5",
            "--k_flow_lastflow",   "0.1",
            "--flow_explore_theta","0.1",
            "--fedprox_k",         "0.001",
        ],
    )


@pytest.mark.skipif(
    not os.path.exists(_MSF_SPLIT),
    reason=(
        "MNIST-SVHN-FASHION split file not found at "
        "datasets/PreciseFCL/data_split/MNISTSVHNFASHION_split_cn10_tn6_cet3_s2571.pkl  "
        "– also ensure MNIST, SVHN and FashionMNIST are pre-downloaded "
        "into datasets/PreciseFCL/."
    ),
)
def test_mnist_svhn_fashion():
    """
    MNIST-SVHN-FASHION
    ------------------
    * Datasets:   must be pre-downloaded into datasets/PreciseFCL/
                  (MNIST, SVHN, FashionMNIST – download=False in dataset.py).
    * Split file: must exist at the path above.
    """
    _run(
        dataset="MNIST-SVHN-FASHION",
        data_split_file="data_split/MNISTSVHNFASHION_split_cn10_tn6_cet3_s2571.pkl",
        n_tasks=6,
        extra_args=[
            "--flow_lr",           "1e-3",
            "--k_loss_flow",       "0.1",
            "--k_flow_lastflow",   "0",
            "--flow_explore_theta","0",
            "--fedprox_k",         "0.001",
        ],
    )


# ---------------------------------------------------------------------------
# Stand-alone runner  (python test_cpu.py)  – no pytest required
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import traceback

    def _check_and_run(fn, skip_path=None, skip_reason=""):
        name = fn.__name__
        if skip_path is not None and not os.path.exists(skip_path):
            print(f"  SKIPPED  {name}\n           {skip_reason}")
            return "skipped"
        try:
            fn()
            print(f"  PASSED   {name}")
            return "passed"
        except Exception:
            print(f"  FAILED   {name}")
            traceback.print_exc()
            return "failed"

    print("\nAF-FCL CPU smoke tests\n" + "=" * 50)

    results = [
        _check_and_run(test_emnist_letters_shuffle),
        _check_and_run(
            test_emnist_letters,
            skip_path=_EMNIST_SPLIT,
            skip_reason="EMNIST-Letters split file not found – supply the .pkl manually.",
        ),
        _check_and_run(
            test_emnist_letters_malicious,
            skip_path=_EMNIST_SPLIT,
            skip_reason="EMNIST-Letters split file not found (shared with malicious variant).",
        ),
        _check_and_run(
            test_cifar100,
            skip_path=_CIFAR_SPLIT,
            skip_reason="CIFAR100 split file not found – run: python generate_cifar100_split.py",
        ),
        _check_and_run(
            test_mnist_svhn_fashion,
            skip_path=_MSF_SPLIT,
            skip_reason=(
                "MNIST-SVHN-FASHION split file not found – supply the .pkl and "
                "pre-download MNIST/SVHN/FashionMNIST into datasets/PreciseFCL/."
            ),
        ),
    ]

    counts = {s: results.count(s) for s in ("passed", "skipped", "failed")}
    print("\n" + "=" * 50)
    print(
        f"Results: {counts['passed']} passed, "
        f"{counts['skipped']} skipped, "
        f"{counts['failed']} failed"
    )
    if counts["failed"]:
        sys.exit(1)
